language: node_js
cache: yarn
node_js:
  - "11"
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
    
script: npm run test
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover:CI